services:
  project:
    command: >
      bash -c "
        npm i
        npm start
      "
    image: mcr.microsoft.com/playwright:focal
    volumes:
      - ./:/app
      - project_node_modules:/app/node_modules
    working_dir: /app

volumes:
  project_node_modules: